include:
  - board: corneish_zen_left//zmk
  - board: corneish_zen_right//zmk
  - board: corneish_zen_left//zmk
    shield: settings_reset
  - board: corneish_zen_right//zmk
    shield: settings_reset
